<a href="https://colab.research.google.com/github/k00dj-19/pytorch_study/blob/main/%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98%20%EB%94%A5%EB%9F%AC%EB%8B%9D%20%EB%A7%88%EC%8A%A4%ED%84%B0/pytorch_deeplearning_master_ch3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!git clone https://github.com/deep-learning-with-pytorch/dlwpt-code.git

Cloning into 'dlwpt-code'...
remote: Enumerating objects: 703, done.
remote: Total 703 (delta 0), reused 0 (delta 0), pack-reused 703
Receiving objects: 100% (703/703), 176.00 MiB | 27.51 MiB/s, done.
Resolving deltas: 100% (309/309), done.
Updating files: 100% (228/228), done.


In [ ]:
a = [1.0, 2.0, 3.0]

In [ ]:
a[0]

1.0

In [ ]:
import torch
a = torch.ones(3)

In [ ]:
a

tensor([1., 1., 1.])

In [ ]:
a[2] = 2.0

In [ ]:
a

tensor([1., 1., 2.])

In [ ]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0

In [ ]:
points

tensor([4., 1., 0., 0., 0., 0.])

In [ ]:
img_t = torch.randn(3,5,5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [ ]:
batch_t = torch.randn(2,3,5,5)
batch_t

tensor([[[[ 1.2126, -0.9870, -0.1235,  0.6689, -1.7292],
          [ 0.2367,  1.1719, -0.0121, -2.1460,  0.5383],
          [ 2.4802, -0.0448, -0.1415, -0.9308,  0.7349],
          [ 0.4649,  0.7798, -0.0568, -0.5921, -1.1069],
          [ 0.3918, -0.7076, -0.5318, -0.5051,  0.0278]],

         [[ 1.9048,  0.0241, -0.1389, -0.3063, -1.1184],
          [-0.2694, -0.1618, -0.2302,  1.1694,  0.0705],
          [-0.0654,  0.4681, -0.3578, -1.4997,  1.5710],
          [-0.0426, -0.7476,  0.5425, -0.7394, -0.8362],
          [ 0.1622,  1.2427,  1.4391,  0.2205, -0.6953]],

         [[ 0.6238, -0.7304, -1.5239, -0.3359,  0.6473],
          [ 0.2190, -0.9755, -0.0048, -0.5334,  0.3277],
          [-1.5027, -0.3006,  0.6540,  1.0267,  0.7843],
          [ 0.0164,  0.5647,  0.9152, -0.9275, -1.3885],
          [ 0.6698,  0.8415, -0.0875,  0.9680,  0.2687]]],


        [[[-1.6612,  0.3894, -0.1310, -0.3676, -0.1188],
          [-1.1514,  1.8524,  0.2749,  0.8966, -2.3028],
          [ 0.2916, -1.

In [ ]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [ ]:
weights.shape, img_t.shape

(torch.Size([3]), torch.Size([3, 5, 5]))

In [ ]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)   # 3 1 1
img_weights = (img_t * unsqueezed_weights)  # 3 5 5 * 3 1 1 = 3 5 5
print(img_weights.shape)
batch_weights = (batch_t * unsqueezed_weights)  # 2 3 5 5 * 3 1 1 = 2 3 5 5
print(batch_weights.shape, batch_t.shape)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
print(batch_weights.shape, batch_t.shape, unsqueezed_weights.shape)
print(img_gray_weighted.shape, batch_gray_weighted.shape)

torch.Size([3, 5, 5])
torch.Size([2, 3, 5, 5]) torch.Size([2, 3, 5, 5])
torch.Size([2, 3, 5, 5]) torch.Size([2, 3, 5, 5]) torch.Size([3, 1, 1])
torch.Size([5, 5]) torch.Size([2, 5, 5])


In [ ]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
img_gray_weighted_fancy.shape,batch_gray_weighted_fancy.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [ ]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

<ipython-input-30-847ddfeff394>:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1788.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [ ]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [ ]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, img_named.shape, weights_named.shape

(torch.Size([3, 1, 1]), torch.Size([3, 5, 5]), torch.Size([3]))

In [ ]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [ ]:
gray_named2 = (img_named[..., :3] * weights_named).sum('channels34')

RuntimeError: ignored

In [ ]:
double_points = torch.ones(10,2,dtype=torch.double)
short_points = torch.tensor([[1,2], [3,4]], dtype=torch.short)

In [ ]:
double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [ ]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0,3.0],[2.0,1.0]])
points.storage()

<ipython-input-43-76de1edb35b1>:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [ ]:
points_storage = points.storage()
points_storage[0]

4.0

In [ ]:
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
a = torch.ones(3,2)
print(a)
a.zero_()
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [ ]:
points = torch.tensor([[4.0,1.0], [5.0,3.0],[2.0,1.0]])
second_point = points[2]
second_point.storage_offset()

4

In [ ]:
second_point.size()

torch.Size([2])

In [ ]:
points.stride()

(2, 1)

In [ ]:
second_point.stride()

(1,)

In [ ]:
import torch
points = torch.tensor([[4.0,1.0], [5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [ ]:
print(id(points.storage()))
print(id(points_t.storage()))

140195186351344
140195186350960


In [ ]:
id(points.storage()) == id(points_t.storage())

False

In [ ]:
print(points.stride())
print(points_t.stride())

(2, 1)
(1, 2)


In [ ]:
import torch
points_gpu = torch.tensor([[4, 1], [5.,3.], [2., 1.]], device='cuda')
points_gpu

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')

In [ ]:
points = 2 * points
points_gpu = 2 * points.to(device='cuda')

In [ ]:
points_gpu = points_gpu + 4

In [ ]:
points_cpu = points_gpu.to(device='cpu')

In [ ]:
points_gpu = points.cuda()
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [ ]:
points = torch.ones(3,4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [ ]:
points = torch.from_numpy(points_np)
points.dtype

torch.float32

In [ ]:
%cd dlwpt-code

/content/dlwpt-code


In [ ]:
points = torch.load("/content/dlwpt-code/data/p1ch3/ourpoints.t")

In [ ]:
points

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ex1 = list(range(9))
print(ex1)
a = torch.tensor(ex1)
print(a)
print(a.shape)
print(a.storage_offset())
print(a.stride())

[0, 1, 2, 3, 4, 5, 6, 7, 8]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
torch.Size([9])
0
(1,)


In [ ]:
b = a.view(3,3)
print(b)
print(b.storage_offset())
print(id(a.storage))
print(id(b.storage))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
0
140598517222080
140594147480320


In [ ]:
c = b[1:, 1:]
print(c)
print(c.storage())
print(c.shape)
print(c.storage_offset())
print(c.stride())

tensor([[4, 5],
        [7, 8]])
 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 9]
torch.Size([2, 2])
4
(3, 1)


In [ ]:
torch.cos(a)

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])